apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calvin-user-worker
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: calvin-user-worker
        role: runtime
        tier: backend
    spec:
      containers:
      - command:
            - /bin/sh
            - -c
            - csruntime --host $(ip route get 8.8.8.8 | awk 'NR==1 {print $NF}') 
              --name calvin-$(ip route get 8.8.8.8 | awk 'NR==1 {print $NF}')
              --loglevel=INFO --attr $(CALVIN_ATTRIBUTES_WORKER)
        env:
        - name: CALVIN_GLOBAL_STORAGE_TYPE
          value: '"proxy"'
          # Replace $(CALVIN_USER_MASTER_SERVICE_PORT_5000_TCP_ADDR) with env variable value
          # Kubernetes don't resolve it
        - name: CALVIN_GLOBAL_STORAGE_PROXY
          value: '"calvinip://$(CALVIN_USER_MASTER_SERVICE_PORT_5000_TCP_ADDR):5000"'
        - name: CALVIN_ATTRIBUTES_WORKER
          value: '"{\"indexed_public\":{\"node_name\":{\"organization\":\"com.ericsson\",\"purpose\":\"distributed-test\",\"group\":\"rest\"}}}"'
        # replace calvin image with yours at dockerhub or private repo
        image: calvinimage
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /id
            port: 5001
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /id
            port: 5001
            scheme: HTTP
          periodSeconds: 60
          initialDelaySeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        name: calvin-user
        ports:
        - containerPort: 5000
          name: data
          protocol: TCP
        - containerPort: 5001
          name: control-api
          protocol: TCP
        - containerPort: 1900
          name: ssdp
          protocol: UDP
        - containerPort: 1901
          name: dht
          protocol: UDP
        - containerPort: 1902
          name: secure-dht
          protocol: UDP
        lifecycle:
          postStart:
            exec:
              command:
                - "touch"
                - "/post-start-run"
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate instead
              command: ["/bin/sh", "-c", "/usr/bin/curl -X DELETE http://$(ip route get 255.255.255.255 | awk '{print $NF}'):5001/node/migrate"]
        resources:
          requests:
            cpu: "910m"
            memory: "60Mi"
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 60
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: calvin-user-worker
spec:
  maxReplicas: 20
  minReplicas: 6
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: calvin-user-worker
  targetCPUUtilizationPercentage: 90
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: calvin-user-worker
  name: calvin-user-service
spec:
  ports:
  - name: calvin-data
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: calvin-control
    port: 5001
    protocol: TCP
    targetPort: 5001
  - name: calvin-ssdp
    port: 1900
    protocol: UDP
    targetPort: 1900
  - name: calvin-ssdp2
    port: 1901
    protocol: UDP
    targetPort: 1901
  - name: calvin-ssdp3
    port: 1902
    protocol: UDP
    targetPort: 1902
  selector:
        app: calvin-user-worker
        role: runtime
        tier: backend
  sessionAffinity: None
  type: NodePort
